name: cozy_living
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1

  shared_preferences: ^2.5.3
  sqflite: ^2.3.3
  path: ^1.9.0

  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/sunny_icon.png"